////
Licensed to the Apache Software Foundation (ASF) under one or more
contributor license agreements. See the NOTICE file distributed with
this work for additional information regarding copyright ownership.
The ASF licenses this file to You under the Apache License, Version 2.0
(the "License"); you may not use this file except in compliance with
the License. You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
////
= Apache Log4j Samples: Gradle Metadata Consumption

This project is an example that validates that, when used in Gradle, Log4j provides transitive dependencies to annotation libraries on the compile classpath.
The example also checks that these libraries are visible when used on the Module Path (JPMS), by including a module-info.java file.
This project is part of the integration tests for a Log4j release.

To build the project, and with that run all validations, run:

[source,shell]
----
./gradlew :log4j-samples-gradle-metadata:build
----

in the samples repository root.
