spring:
  cloud:
    bus:
      enabled: true
    config:
      server:
#        git:
#          uri:
#          searchPaths: "{application},{application}/{profile}"
        native:
          searchLocations: file:///${user.dir}/config-repo,file:///${user.dir}/config-repo/{application},file:///${user.dir}/config-repo/{application}/{profile}

  security:
    user:
      name: guest
      password: guest

  rabbitmq:
    addresses: localhost
    port: 5672
    username: guest
    password: guest

  profiles:
    active: native

server:
    port:                                                 8888

    servlet:
     context-path:                                       /ConfigService

management:
    endpoints:
        web:
            base-path: /
            exposure:
                include:                                  health, info, refresh
