#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to you under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: graalvm-reusable-test

on:
  workflow_call:
    inputs:
      log4j-version:
        description: Version of Log4j Core
        type: string
        # Should point to the current 2.x snapshot version
        default: 2.25.0-SNAPSHOT
      log4j-repository-url:
        description: Staging Maven repository. Should be empty for snapshots.
        type: string
        default: ''
      samples-ref:
        description: The branch, tag or SHA of `logging-log4j-samples` to checkout
        type: string
        default: ${{ github.ref }}

permissions: read-all

jobs:

  graalvm-test:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        backend: [ jul, log4j-core-minimal, log4j-core, log4j-core-jtl-minimal, log4j-core-jtl, logback, simple]

    steps:

      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8   # 5.0.0
        with:
          repository: 'apache/logging-log4j-samples'
          ref: ${{ inputs.samples-ref }}

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@aba6a077d71fbfc02138d7470c4ad6e7f85bd2a9   # 1.3.7
        with:
          java-version: '21'

      - name: Build
        id: build
        shell: bash
        env:
          LOG4J_VERSION: ${{ inputs.log4j-version }}
          LOG4J_REPOSITORY_URL: ${{ inputs.log4j-repository-url }}
          MAVEN_PROFILE: use-${{ matrix.backend }}
        run: |
          ./mvnw -f log4j-samples-graalvm \
            --show-version --batch-mode --errors --no-transfer-progress \
            -Dlog4j.version=$LOG4J_VERSION -Dlog4j.repository.url=$LOG4J_REPOSITORY_URL\
            -P$MAVEN_PROFILE \
            clean verify
